services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: roadmap-db
    environment:
      POSTGRES_DB: roadmap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d roadmap"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - roadmap-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: roadmap-backend
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/roadmap
      JWT_SECRET: dev-secret-change-in-production
      PWD_SALT: dev-salt-change-in-production
      ENVIRONMENT: production
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/logs:/app/logs
    restart: unless-stopped
    networks:
      - roadmap-network
    healthcheck:
      test: ["CMD", "poetry", "run", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: roadmap-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - roadmap-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis для кэширования (опционально)
  redis:
    image: redis:7-alpine
    container_name: roadmap-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - roadmap-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  roadmap-network:
    driver: bridge
