"""add_admin_fields_and_node_blocks

Revision ID: aa3c695d9636
Revises: 949cbd351ffe
Create Date: 2025-09-08 00:45:16.654402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3c695d9636'
down_revision: Union[str, Sequence[str], None] = '949cbd351ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем новые поля в roadmap_nodes
    op.add_column('roadmap_nodes', sa.Column('node_type', sa.String(length=20), nullable=False, server_default='task'))
    op.add_column('roadmap_nodes', sa.Column('is_required', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('roadmap_nodes', sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('roadmap_nodes', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    
    # Создаем таблицу node_blocks
    op.create_table('node_blocks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('blocking_node_id', sa.Integer(), nullable=False),
        sa.Column('blocked_node_id', sa.Integer(), nullable=False),
        sa.Column('block_type', sa.String(length=20), nullable=False, server_default='required'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.ForeignKeyConstraint(['blocking_node_id'], ['roadmap_nodes.id'], ),
        sa.ForeignKeyConstraint(['blocked_node_id'], ['roadmap_nodes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_blocks_id'), 'node_blocks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем таблицу node_blocks
    op.drop_index(op.f('ix_node_blocks_id'), table_name='node_blocks')
    op.drop_table('node_blocks')
    
    # Удаляем новые поля из roadmap_nodes
    op.drop_column('roadmap_nodes', 'is_active')
    op.drop_column('roadmap_nodes', 'order_index')
    op.drop_column('roadmap_nodes', 'is_required')
    op.drop_column('roadmap_nodes', 'node_type')
    # ### end Alembic commands ###
