"""Initial migration

Revision ID: b25c29ada68d
Revises: 
Create Date: 2025-09-07 21:01:00.134236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25c29ada68d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('checkpoint', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_nodes_direction'), 'roadmap_nodes', ['direction'], unique=False)
    op.create_index(op.f('ix_roadmap_nodes_id'), 'roadmap_nodes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('badges', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['roadmap_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'node_id'),
    sa.UniqueConstraint('user_id', 'node_id', name='uq_progress_user_node')
    )
    op.create_table('roadmap_node_links',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['roadmap_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['roadmap_nodes.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'target_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roadmap_node_links')
    op.drop_table('progress')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roadmap_nodes_id'), table_name='roadmap_nodes')
    op.drop_index(op.f('ix_roadmap_nodes_direction'), table_name='roadmap_nodes')
    op.drop_table('roadmap_nodes')
    # ### end Alembic commands ###
